// packages/__internals/testing/src/kitchen-sink/react-shell.react.tsx
/** @jsxImportSource react */
import { eco } from '@ecopages/core';
import type { EcoChildren } from '@ecopages/core';
import type { ReactNode } from 'react';

type ReactShellProps = {
	id: string;
	children?: ReactNode | EcoChildren;
};

export const ReactShell = eco.component<ReactShellProps, ReactNode>({
	integration: 'react',
	render: ({ id, children }) => {
		const body =
			typeof children === 'string' ? (
				<div className="integration-shell__body" dangerouslySetInnerHTML={{ __html: children }} />
			) : (
				<div className="integration-shell__body">{children as ReactNode}</div>
			);

		return (
			<section className="integration-shell integration-shell--react" data-react-shell={id}>
				<p className="integration-shell__label">React shell · {id}</p>
				{body}
			</section>
		);
	},
});

// packages/__internals/testing/src/kitchen-sink/lit-shell.lit.tsx
import { eco } from '@ecopages/core';
import { html, nothing, type TemplateResult } from 'lit';
import { unsafeHTML } from 'lit/directives/unsafe-html.js';

type LitShellProps = {
	id: string;
	children?: unknown;
};

export const LitShell = eco.component<LitShellProps, TemplateResult<1>>({
	integration: 'lit',
	render: ({ id, children }) =>
		html`<section class="integration-shell integration-shell--lit" data-lit-shell=${id}>
			<p class="integration-shell__label">Lit shell · ${id}</p>
			<div class="integration-shell__body">
				${typeof children === 'string' ? unsafeHTML(children) : (children ?? nothing)}
			</div>
		</section>`,
});
