// packages/core/src/integrations/lit/lit-renderer.ts
import { IntegrationRenderer, type IntegrationRendererRenderOptions } from '@/route-renderer/integration-renderer';
import type { RouteRendererBody } from '@/route-renderer/route-renderer';
import { render } from '@lit-labs/ssr';
import { RenderResultReadable } from '@lit-labs/ssr/lib/render-result-readable';
import { unsafeHTML } from 'lit/directives/unsafe-html.js';
import { litPlugin } from './lit.plugin';

export class LitRenderer extends IntegrationRenderer {
  name = litPlugin.name;

  async render({
    params,
    query,
    props,
    metadata,
    Page,
    HtmlTemplate,
  }: IntegrationRendererRenderOptions): Promise<RouteRendererBody> {
    try {
      const children = await Page({ params, query, ...props });

      const template = await HtmlTemplate({
        metadata,
        headContent: await this.getHeadContent(Page.dependencies),
        children: '<--content-->',
      });

      const [templateStart, templateEnd] = template.split('<--content-->');

      const DOC_TYPE = this.DOC_TYPE;

      function* streamBody() {
        yield DOC_TYPE;
        yield templateStart;
        yield* render(unsafeHTML(children));
        yield templateEnd;
      }

      return new RenderResultReadable(streamBody());
    } catch (error) {
      throw new Error(`[eco-pages] Error rendering page: ${error}`);
    }
  }
}

// packages/core/src/integrations/react/react-renderer.ts
import type { RouteRendererBody } from '@/route-renderer/route-renderer';
import { IntegrationRenderer, type IntegrationRendererRenderOptions } from '@eco-pages/core';
import { renderToReadableStream } from 'react-dom/server';
import { DynamicHead, reactPlugin } from './react.plugin';

export class ReactRenderer extends IntegrationRenderer {
  name = reactPlugin.name;

  async render({
    params,
    query,
    props,
    metadata,
    Page,
    HtmlTemplate,
  }: IntegrationRendererRenderOptions): Promise<RouteRendererBody> {
    try {
      const body = await renderToReadableStream(
        HtmlTemplate({
          metadata,
          dependencies: Page.dependencies,
          headContent: DynamicHead({ dependencies: Page.dependencies }),
          children: Page({ params, query, ...props }),
        }),
      );

      return body;
    } catch (error) {
      throw new Error(`[eco-pages] Error rendering page: ${error}`);
    }
  }
}
