// playground/kitchen-sink-nitro/src/pages/integration-matrix/react-entry.react.tsx
/** @jsxImportSource react */
import { eco } from '@ecopages/core';
import { KitaCounter } from '@/components/kita-counter.kita';
import { LitCounter } from '@/components/lit-counter.lit';
import { ReactCounter } from '@/components/react-counter.react';
import { ReactShell } from '@/components/react-shell.react';
import { ReactPlaygroundLayout } from '@/layouts/react-playground-layout';
import type { ReactNode } from 'react';

export default eco.page<{}, ReactNode>({
	integration: 'react',
	layout: ReactPlaygroundLayout,
	dependencies: {
		components: [ReactPlaygroundLayout, ReactShell, KitaCounter, LitCounter, ReactCounter],
		stylesheets: ['./integration-matrix.css'],
	},
	metadata: () => ({
		title: 'React Entry Matrix',
		description: 'React-first shell inside the kitchen-sink matrix route.',
	}),
	render: () => (
		<div className="space-y-8">
			<section className="card space-y-4">
				<p className="text-xs font-semibold uppercase tracking-[0.28em] text-sky-600">React shell entry</p>
				<h1 className="font-display text-4xl font-semibold tracking-tight">
					The React boundary can anchor the route without owning the whole page.
				</h1>
				<p className="max-w-3xl text-base leading-8 text-muted">
					This follows the e2e kitchen-sink pattern more closely: the file-system page remains Kita-based
					while the primary interactive shell is React and still nests Lit and Kita content inside it.
				</p>
			</section>

			<ReactShell id="react-entry-root">react-entry-child</ReactShell>

			<section className="integration-shell integration-shell--kita" data-kita-shell="react-entry-kita-child">
				<p className="integration-shell__label">Kita shell · react-entry-kita-child</p>
				<div className="integration-shell__body">
					<section
						className="integration-shell integration-shell--lit"
						data-lit-shell="react-entry-lit-child"
					>
						<p className="integration-shell__label">Lit shell · react-entry-lit-child</p>
						<div className="integration-shell__body">
							<span data-cross-child="react-entry">react-entry-nested-child</span>
						</div>
					</section>
				</div>
			</section>

			<section className="card space-y-4">
				<p className="text-xs uppercase tracking-[0.24em] text-muted">Counters</p>
				<div className="flex flex-wrap gap-3">
					<div className="integration-counter" data-kita-counter>
						<button className="integration-counter__button" type="button" data-kita-inc>
							+
						</button>
						<span className="integration-counter__value" data-kita-value>
							0
						</span>
					</div>
					<LitCounter count={0} />
					<ReactCounter />
				</div>
				<a className="text-xs underline text-muted" href="/react-content">
					View React MDX page
				</a>
			</section>
		</div>
	),
});

// playground/kitchen-sink/src/pages/integration-matrix/lit-entry.lit.tsx
import { eco } from '@ecopages/core';
import type { EcoPagesElement } from '@ecopages/core';
import { html } from 'lit/static-html.js';
import {
	integrationMatrixHostShellIds,
	integrationMatrixHostShellLeafText,
	integrationMatrixShellCounterCases,
	integrationMatrixTestIds,
} from '@/data/integration-matrix';
import { BaseLayout } from '@/layouts/base-layout';
import { IntegrationCounterGroup } from '@/components/integration-counter-group.kita';
import { EcopagesJsxShell } from '@ecopages/testing/kitchen-sink/ecopages-jsx-shell';
import { KitaShell } from '@ecopages/testing/kitchen-sink/kita-shell';
import { LitShell } from '@ecopages/testing/kitchen-sink/lit-shell';
import { ReactShell } from '@ecopages/testing/kitchen-sink/react-shell';

export default eco.page<{}, EcoPagesElement>({
	integration: 'lit',
	dependencies: {
		components: [BaseLayout, IntegrationCounterGroup, KitaShell, LitShell, EcopagesJsxShell, ReactShell],
		stylesheets: ['./integration-matrix.css'],
	},
	layout: BaseLayout,
	metadata: () => ({
		title: 'Lit Entry Matrix',
		description: 'Lit-first route that renders the same shared shell stack and counter set as the other hosts.',
	}),
	render: () =>
		html`<div class="space-y-8">
			<section class="card space-y-4">
				<p class="text-xs font-semibold uppercase tracking-[0.28em] text-sky-600">Lit route entry</p>
				<h1 class="font-display text-4xl font-semibold tracking-tight">
					Each host page should expose the same shell stack and the same four counters.
				</h1>
				<p class="max-w-3xl text-base leading-8 text-muted">
					This route keeps Lit as the page entry while rendering the same nested shell composition and counter
					set used by the Kita, React, and Ecopages JSX host pages.
				</p>
			</section>

			<section class="card space-y-4" data-testid=${integrationMatrixTestIds.hostShellStack}>
				<p class="text-xs uppercase tracking-[0.24em] text-muted">Shared host shell stack</p>
				${eco.embed(
					LitShell,
					{ id: integrationMatrixHostShellIds.lit },
					eco.embed(
						KitaShell,
						{ id: integrationMatrixHostShellIds.kita },
						eco.embed(
							ReactShell,
							{ id: integrationMatrixHostShellIds.react },
							eco.embed(
								EcopagesJsxShell,
								{ id: integrationMatrixHostShellIds['ecopages-jsx'] },
								integrationMatrixHostShellLeafText,
							),
						),
					),
				)}
			</section>

			<section class="card space-y-4">
				<p class="text-xs uppercase tracking-[0.24em] text-muted">Counters</p>
				${IntegrationCounterGroup({
					testId: integrationMatrixTestIds.litCounters,
					radiantId: 'lit-entry-radiant',
				})}
			</section>

			<section class="card space-y-4" data-testid=${integrationMatrixTestIds.shellCounters}>
				<p class="text-xs uppercase tracking-[0.24em] text-muted">Every counter inside every shell</p>
				<div class="grid gap-4 lg:grid-cols-2 xl:grid-cols-4">
					${integrationMatrixShellCounterCases.map((item) =>
						eco.embed(
							{
								kita: KitaShell,
								lit: LitShell,
								react: ReactShell,
								'ecopages-jsx': EcopagesJsxShell,
							}[item.shell],
							{ id: item.shellId },
							IntegrationCounterGroup({ testId: item.testId, radiantId: item.radiantId }),
						),
					)}
				</div>
			</section>
		</div>` as unknown as EcoPagesElement,
});
