// playground/kitchen-sink/src/components/lit-counter.lit.tsx
import { eco } from '@ecopages/core';
import type { EcoPagesElement } from '@ecopages/core';
import { html } from 'lit';
import type { LitCounterProps } from './lit-counter.script';

export const LitCounter = eco.component<LitCounterProps, EcoPagesElement>({
	integration: 'lit',
	dependencies: {
		scripts: ['./lit-counter.script.ts'],
	},
	render: ({ count = 0 }) =>
		html`<lit-counter count=${count} data-counter-kind="lit"></lit-counter>` as unknown as EcoPagesElement,
});

// playground/kitchen-sink/src/components/react-counter.react.tsx
/** @jsxImportSource react */
import { eco } from '@ecopages/core';
import { useState, type ReactNode } from 'react';

export const ReactCounter = eco.component<{}, ReactNode>({
	integration: 'react',
	dependencies: {
		stylesheets: ['./integration-counter.css', './react-counter.css'],
	},
	render: () => {
		const [count, setCount] = useState(0);

		return (
			<div className="integration-counter" data-react-counter data-counter-kind="react">
				<button
					className="integration-counter__button"
					type="button"
					data-react-inc
					onClick={() => setCount((value) => value + 1)}
				>
					+
				</button>
				<span className="integration-counter__value" data-react-value>
					{count}
				</span>
			</div>
		);
	},
});
