// playground/kitchen-sink/src/components/lit-counter.lit.tsx
import { eco } from '@ecopages/core';
import type { EcoPagesElement } from '@ecopages/core';
import type { LitCounterProps } from './lit-counter.script';

export const LitCounter = eco.component<LitCounterProps, EcoPagesElement>({
	integration: 'lit',
	dependencies: {
		scripts: [
			{
				lazy: { 'on:interaction': 'click,mouseenter,focusin' },
				src: './lit-counter.script.ts',
				ssr: true,
			},
		],
	},
	render: ({ count = 0 }) => <lit-counter count={count}></lit-counter>,
});

// playground/kitchen-sink/src/components/dependency-discovery/counter.lit.tsx
import { eco, type EcoPagesElement } from '@ecopages/core';
import { html } from 'lit';
import './counter.css';

export const DiscoveryCounter = eco.component({
	dependencies: {
		scripts: [{ src: './counter.script.ts', ssr: true, lazy: { 'on:visible': true } }],
	},
	render: () =>
		html`<div class="discovery-counter-host">
			<discovery-counter></discovery-counter>
		</div>` as unknown as EcoPagesElement,
});
