// packages/integrations/lit/src/lit-renderer.ts
/**
 * This module contains the Lit renderer
 * @module
 */

import { IntegrationRenderer, type IntegrationRendererRenderOptions, type RouteRendererBody } from '@ecopages/core';
import { render } from '@lit-labs/ssr';
import { RenderResultReadable } from '@lit-labs/ssr/lib/render-result-readable.js';
import { unsafeHTML } from 'lit/directives/unsafe-html.js';
import { PLUGIN_NAME } from './lit.plugin.ts';

/**
 * A renderer for the Lit integration.
 */
export class LitRenderer extends IntegrationRenderer {
  name = PLUGIN_NAME;

  async render({
    params,
    query,
    props,
    metadata,
    dependencies,
    Page,
    HtmlTemplate,
  }: IntegrationRendererRenderOptions): Promise<RouteRendererBody> {
    try {
      const children = await Page({ params, query, ...props });

      const template = (await HtmlTemplate({
        metadata,
        headContent: await this.getHeadContent(dependencies),
        children: '<--content-->',
      })) as string;

      const [templateStart, templateEnd] = template.split('<--content-->');

      const DOC_TYPE = this.DOC_TYPE;

      function* streamBody() {
        yield DOC_TYPE;
        yield templateStart;
        yield* render(unsafeHTML(children));
        yield templateEnd;
      }

      return new RenderResultReadable(streamBody());
    } catch (error) {
      throw new Error(`[ecopages] Error rendering page: ${error}`);
    }
  }
}

// packages/react/src/react-renderer.ts
import {
  type EcoComponentDependencies,
  type EcoPagesConfig,
  IntegrationRenderer,
  type IntegrationRendererRenderOptions,
  type RouteRendererBody,
} from '@eco-pages/core';
import React from 'react';
import { renderToReadableStream } from 'react-dom/server';
import { PLUGIN_NAME } from './react.plugin';

export class ReactRenderer extends IntegrationRenderer {
  name = PLUGIN_NAME;

  collectDependencies({
    dependencies,
    appConfig,
  }: { dependencies?: EcoComponentDependencies; appConfig: EcoPagesConfig }) {
    return {
      stylesheets: [
        ...(dependencies?.stylesheets || []),
        ...appConfig.integrationsDependencies
          .filter((dep) => dep.kind === 'stylesheet')
          .flatMap((dep) => dep.filePath.split(`${appConfig.distDir}/`)[1]),
      ],
      scripts: [
        ...(dependencies?.scripts || []),
        ...appConfig.integrationsDependencies
          .filter((dep) => dep.kind === 'script')
          .flatMap((dep) => dep.filePath.split(`${appConfig.distDir}/`)[1]),
      ],
    };
  }

  createDynamicHead({ dependencies }: { dependencies?: EcoComponentDependencies }) {
    if (!dependencies) return React.createElement(React.Fragment, null);

    const elements: React.JSX.Element[] = [];

    if (dependencies.stylesheets?.length) {
      for (const stylesheet of dependencies.stylesheets) {
        elements.push(
          React.createElement('link', { key: stylesheet, rel: 'stylesheet', href: stylesheet, as: 'style' }),
        );
      }
    }
    if (dependencies.scripts?.length) {
      for (const script of dependencies.scripts) {
        elements.push(React.createElement('script', { key: script, defer: true, type: 'module', src: script }));
      }
    }

    return React.createElement(React.Fragment, null, elements);
  }

  async render({
    appConfig,
    params,
    query,
    props,
    metadata,
    Page,
    HtmlTemplate,
  }: IntegrationRendererRenderOptions): Promise<RouteRendererBody> {
    try {
      const body = await renderToReadableStream(
        await HtmlTemplate({
          metadata,
          dependencies: Page.dependencies,
          headContent: this.createDynamicHead({
            dependencies: this.collectDependencies({ dependencies: Page.dependencies, appConfig }),
          }),
          children: Page({ params, query, ...props }),
        }),
      );

      return body;
    } catch (error) {
      throw new Error(`[eco-pages] Error rendering page: ${error}`);
    }
  }
}
