// packages/integrations/react/src/react-renderer.tsx
import {
  type EcoComponentDependencies,
  IntegrationRenderer,
  type IntegrationRendererRenderOptions,
  type RouteRendererBody,
} from '@ecopages/core';
import { renderToReadableStream } from 'react-dom/server';
import { Fragment } from 'react/jsx-runtime';
import { PLUGIN_NAME } from './react.plugin';

export class ReactRenderer extends IntegrationRenderer {
  name = PLUGIN_NAME;

  createDynamicHead({ dependencies }: { dependencies?: EcoComponentDependencies }) {
    const elements: React.JSX.Element[] = [];
    if (dependencies) {
      if (dependencies.stylesheets?.length) {
        for (const stylesheet of dependencies.stylesheets) {
          const linkElement = <link key={stylesheet} rel="stylesheet" href={stylesheet} as="style" />;
          elements.push(linkElement);
        }
      }

      if (dependencies.scripts?.length) {
        for (const script of dependencies.scripts) {
          const scriptElement = <script key={script} defer type="module" src={script} />;
          elements.push(scriptElement);
        }
      }
    }

    return <Fragment>{elements}</Fragment>;
  }

  async render({
    params,
    query,
    props,
    metadata,
    dependencies,
    Page,
    HtmlTemplate,
  }: IntegrationRendererRenderOptions): Promise<RouteRendererBody> {
    try {
      const body = await renderToReadableStream(
        <HtmlTemplate metadata={metadata} headContent={this.createDynamicHead({ dependencies })}>
          <Page params={params} query={query} {...props} />
        </HtmlTemplate>,
      );

      return body as any;
    } catch (error) {
      throw new Error(`[ecopages] Error rendering page: ${error}`);
    }
  }
}

// packages/integrations/lit/src/lit-renderer.ts
/**
 * This module contains the Lit renderer
 * @module
 */

import { IntegrationRenderer, type IntegrationRendererRenderOptions, type RouteRendererBody } from '@ecopages/core';
import { render } from '@lit-labs/ssr';
import { RenderResultReadable } from '@lit-labs/ssr/lib/render-result-readable.js';
import { unsafeHTML } from 'lit/directives/unsafe-html.js';
import { PLUGIN_NAME } from './lit.plugin.ts';

/**
 * A renderer for the Lit integration.
 */
export class LitRenderer extends IntegrationRenderer {
  name = PLUGIN_NAME;

  async render({
    params,
    query,
    props,
    metadata,
    dependencies,
    Page,
    HtmlTemplate,
  }: IntegrationRendererRenderOptions): Promise<RouteRendererBody> {
    try {
      const children = await Page({ params, query, ...props });

      const template = (await HtmlTemplate({
        metadata,
        headContent: await this.getHeadContent(dependencies),
        children: '<--content-->',
      })) as string;

      const [templateStart, templateEnd] = template.split('<--content-->');

      const DOC_TYPE = this.DOC_TYPE;

      function* streamBody() {
        yield DOC_TYPE;
        yield templateStart;
        yield* render(unsafeHTML(children));
        yield templateEnd;
      }

      return new RenderResultReadable(streamBody());
    } catch (error) {
      throw new Error(`[ecopages] Error rendering page: ${error}`);
    }
  }
}
