// playground/kitchen-sink/src/components/lit-counter.lit.tsx
import { eco } from '@ecopages/core';
import type { EcoPagesElement } from '@ecopages/core';
import { html } from 'lit';
import type { LitCounterProps } from './lit-counter.script';

export const LitCounter = eco.component<LitCounterProps, EcoPagesElement>({
	integration: 'lit',
	dependencies: {
		scripts: [{ src: './lit-counter.script.ts', ssr: true }],
	},
	render: ({ count = 0 }) =>
		html`<lit-counter count=${count} data-counter-kind="lit"></lit-counter>` as unknown as EcoPagesElement,
});

// apps/docs/src/components/lit-counter/index.tsx
import { eco } from '@ecopages/core';
import type { LitCounterProps } from './lit-counter.script';

export const LitCounter = eco.component<LitCounterProps>({
	dependencies: {
		scripts: [{ src: './lit-counter.script.ts', ssr: true }],
	},
	render: ({ count = 0 }) => {
		return <lit-counter count={count}></lit-counter>;
	},
});
